import { applyRules } from './shared';

const RULES = [
  // Software / tech (most common first)
  { pattern: /\bapplication\b/gi, replacement: 'app' },
  { pattern: /\bapplications\b/gi, replacement: 'apps' },
  { pattern: /\bconfiguration\b/gi, replacement: 'config' },
  { pattern: /\bconfigurations\b/gi, replacement: 'configs' },
  { pattern: /\brequirement\b/gi, replacement: 'req' },
  { pattern: /\brequirements\b/gi, replacement: 'reqs' },
  { pattern: /\bimplementations?\b/gi, replacement: 'impl' },
  { pattern: /\bauthentication\b/gi, replacement: 'auth' },
  { pattern: /\bauthorization\b/gi, replacement: 'authz' },
  { pattern: /\bdocumentation\b/gi, replacement: 'docs' },
  { pattern: /\brepository\b/gi, replacement: 'repo' },
  { pattern: /\brepositories\b/gi, replacement: 'repos' },
  { pattern: /\bdependency\b/gi, replacement: 'dep' },
  { pattern: /\bdependencies\b/gi, replacement: 'deps' },
  { pattern: /\brequest\b/gi, replacement: 'req' },
  { pattern: /\brequests\b/gi, replacement: 'reqs' },
  { pattern: /\bresponse\b/gi, replacement: 'res' },
  { pattern: /\bresponses\b/gi, replacement: 'ress' },
  { pattern: /\benvironment\b/gi, replacement: 'env' },
  { pattern: /\benvironments\b/gi, replacement: 'envs' },
  { pattern: /\bdevelopment\b/gi, replacement: 'dev' },
  { pattern: /\bproduction\b/gi, replacement: 'prod' },
  { pattern: /\bstaging\b/gi, replacement: 'stg' },
  { pattern: /\btemporary\b/gi, replacement: 'tmp' },
  { pattern: /\btemporarily\b/gi, replacement: 'tmply' },
  { pattern: /\bmaximum\b/gi, replacement: 'max' },
  { pattern: /\bminimum\b/gi, replacement: 'min' },
  { pattern: /\bparameter\b/gi, replacement: 'param' },
  { pattern: /\bparameters\b/gi, replacement: 'params' },
  { pattern: /\bargument\b/gi, replacement: 'arg' },
  { pattern: /\barguments\b/gi, replacement: 'args' },
  { pattern: /\bvariable\b/gi, replacement: 'var' },
  { pattern: /\bvariables\b/gi, replacement: 'vars' },
  { pattern: /\bfunction\b/gi, replacement: 'fn' },
  { pattern: /\bfunctions\b/gi, replacement: 'fns' },
  { pattern: /\bobject\b/gi, replacement: 'obj' },
  { pattern: /\bobjects\b/gi, replacement: 'objs' },
  { pattern: /\bstring\b/gi, replacement: 'str' },
  { pattern: /\bstrings\b/gi, replacement: 'strs' },
  { pattern: /\bnumber\b/gi, replacement: 'num' },
  { pattern: /\bnumbers\b/gi, replacement: 'nums' },
  { pattern: /\bboolean\b/gi, replacement: 'bool' },
  { pattern: /\bbooleans\b/gi, replacement: 'bools' },
  { pattern: /\binteger\b/gi, replacement: 'int' },
  { pattern: /\bintegers\b/gi, replacement: 'ints' },
  { pattern: /\berror\b/gi, replacement: 'err' },
  { pattern: /\berrors\b/gi, replacement: 'errs' },
  { pattern: /\bmessage\b/gi, replacement: 'msg' },
  { pattern: /\bmessages\b/gi, replacement: 'msgs' },
  { pattern: /\bexception\b/gi, replacement: 'exc' },
  { pattern: /\bexceptions\b/gi, replacement: 'excs' },
  { pattern: /\breference\b/gi, replacement: 'ref' },
  { pattern: /\breferences\b/gi, replacement: 'refs' },
  { pattern: /\bidentifier\b/gi, replacement: 'id' },
  { pattern: /\bidentifiers\b/gi, replacement: 'ids' },
  { pattern: /\bindex\b/gi, replacement: 'idx' },
  { pattern: /\bindices\b/gi, replacement: 'idxs' },
  { pattern: /\bindexes\b/gi, replacement: 'idxs' },
  { pattern: /\bcurrent\b/gi, replacement: 'curr' },
  { pattern: /\bprevious\b/gi, replacement: 'prev' },
  { pattern: /\bnext\b/gi, replacement: 'nxt' },
  { pattern: /\bdefault\b/gi, replacement: 'def' },
  { pattern: /\bpackage\b/gi, replacement: 'pkg' },
  { pattern: /\bpackages\b/gi, replacement: 'pkgs' },
  { pattern: /\blibrary\b/gi, replacement: 'lib' },
  { pattern: /\blibraries\b/gi, replacement: 'libs' },
  { pattern: /\butilities\b/gi, replacement: 'utils' },
  { pattern: /\butility\b/gi, replacement: 'util' },
  { pattern: /\bcomponent\b/gi, replacement: 'comp' },
  { pattern: /\bcomponents\b/gi, replacement: 'comps' },
  { pattern: /\bproperty\b/gi, replacement: 'prop' },
  { pattern: /\bproperties\b/gi, replacement: 'props' },
  { pattern: /\battribute\b/gi, replacement: 'attr' },
  { pattern: /\battributes\b/gi, replacement: 'attrs' },
  { pattern: /\bevent\b/gi, replacement: 'evt' },
  { pattern: /\bevents\b/gi, replacement: 'evts' },
  { pattern: /\bhandler\b/gi, replacement: 'hndlr' },
  { pattern: /\bhandlers\b/gi, replacement: 'hndlrs' },
  { pattern: /\blistener\b/gi, replacement: 'lstnr' },
  { pattern: /\blisteners\b/gi, replacement: 'lstnrs' },
  { pattern: /\boperation\b/gi, replacement: 'op' },
  { pattern: /\boperations\b/gi, replacement: 'ops' },
  { pattern: /\boperator\b/gi, replacement: 'op' },
  { pattern: /\boperators\b/gi, replacement: 'ops' },
  { pattern: /\bexpression\b/gi, replacement: 'expr' },
  { pattern: /\bexpressions\b/gi, replacement: 'exprs' },
  { pattern: /\bstatement\b/gi, replacement: 'stmt' },
  { pattern: /\bstatements\b/gi, replacement: 'stmts' },
  { pattern: /\bdeclaration\b/gi, replacement: 'decl' },
  { pattern: /\bdeclarations\b/gi, replacement: 'decls' },
  { pattern: /\bdefinition\b/gi, replacement: 'def' },
  { pattern: /\bdefinitions\b/gi, replacement: 'defs' },
  { pattern: /\basynchronous\b/gi, replacement: 'async' },
  { pattern: /\bsynchronous\b/gi, replacement: 'sync' },
  { pattern: /\bregular expression\b/gi, replacement: 'regex' },
  { pattern: /\bregular expressions\b/gi, replacement: 'regexes' },
  { pattern: /\bdatabase\b/g, replacement: 'DB' },
  { pattern: /\bdatabases\b/gi, replacement: 'DBs' },
  { pattern: /\bkubernetes\b/gi, replacement: 'k8s' },
  { pattern: /\binternationalization\b/gi, replacement: 'i18n' },
  { pattern: /\blocalization\b/gi, replacement: 'l10n' },
  { pattern: /\baccessibility\b/gi, replacement: 'a11y' },
  { pattern: /\bserialization\b/gi, replacement: 'ser' },
  { pattern: /\bdeserialization\b/gi, replacement: 'deser' },
  { pattern: /\bconfiguration file\b/gi, replacement: 'config' },
  { pattern: /\bconfiguration files\b/gi, replacement: 'configs' },
  { pattern: /\benv var\b/gi, replacement: 'env' },
  { pattern: /\benv vars\b/gi, replacement: 'envs' },
  { pattern: /\benvironment variable\b/gi, replacement: 'env' },
  { pattern: /\benvironment variables\b/gi, replacement: 'envs' },
  { pattern: /\bcommand line\b/gi, replacement: 'CLI' },
  { pattern: /\bcommand-line interface\b/gi, replacement: 'CLI' },
  { pattern: /\buser interface\b/gi, replacement: 'UI' },
  { pattern: /\bgraphical user interface\b/gi, replacement: 'GUI' },
  { pattern: /\bapplication programming interface\b/gi, replacement: 'API' },
  { pattern: /\bcontinuous integration\b/gi, replacement: 'CI' },
  { pattern: /\bcontinuous deployment\b/gi, replacement: 'CD' },
  { pattern: /\bcontinuous delivery\b/gi, replacement: 'CD' },
  { pattern: /\bversion control\b/gi, replacement: 'VCS' },
  { pattern: /\bsource control\b/gi, replacement: 'VCS' },
  { pattern: /\boperating system\b/gi, replacement: 'OS' },
  { pattern: /\bobject-oriented\b/gi, replacement: 'OO' },
  { pattern: /\bfunctional programming\b/gi, replacement: 'FP' },
  { pattern: /\bobject-oriented programming\b/gi, replacement: 'OOP' },
  { pattern: /\btest-driven development\b/gi, replacement: 'TDD' },
  { pattern: /\bbehavior-driven development\b/gi, replacement: 'BDD' },
  { pattern: /\bdomain-driven design\b/gi, replacement: 'DDD' },
  { pattern: /\bsingle responsibility principle\b/gi, replacement: 'SRP' },
  { pattern: /\bopen closed principle\b/gi, replacement: 'OCP' },
  { pattern: /\bliskov substitution principle\b/gi, replacement: 'LSP' },
  { pattern: /\binterface segregation principle\b/gi, replacement: 'ISP' },
  { pattern: /\bdependency inversion principle\b/gi, replacement: 'DIP' },
  { pattern: /\bdon't repeat yourself\b/gi, replacement: 'DRY' },
  { pattern: /\bkeep it simple stupid\b/gi, replacement: 'KISS' },
  { pattern: /\byou aren't gonna need it\b/gi, replacement: 'YAGNI' },
  { pattern: /\bread-eval-print loop\b/gi, replacement: 'REPL' },
  { pattern: /\bintegrated development environment\b/gi, replacement: 'IDE' },
  { pattern: /\bsoftware development kit\b/gi, replacement: 'SDK' },
  { pattern: /\bsoftware as a service\b/gi, replacement: 'SaaS' },
  { pattern: /\bplatform as a service\b/gi, replacement: 'PaaS' },
  { pattern: /\binfrastructure as a service\b/gi, replacement: 'IaaS' },
  { pattern: /\bfunction as a service\b/gi, replacement: 'FaaS' },
  { pattern: /\bcontent delivery network\b/gi, replacement: 'CDN' },
  { pattern: /\bload balancer\b/gi, replacement: 'LB' },
  { pattern: /\bvirtual machine\b/gi, replacement: 'VM' },
  { pattern: /\bvirtual machines\b/gi, replacement: 'VMs' },
  { pattern: /\bvirtual private network\b/gi, replacement: 'VPN' },
  { pattern: /\bsecure shell\b/gi, replacement: 'SSH' },
  { pattern: /\bhypertext transfer protocol\b/gi, replacement: 'HTTP' },
  { pattern: /\bhypertext transfer protocol secure\b/gi, replacement: 'HTTPS' },
  { pattern: /\buniform resource locator\b/gi, replacement: 'URL' },
  { pattern: /\buniform resource identifier\b/gi, replacement: 'URI' },
  { pattern: /\bplain old javascript object\b/gi, replacement: 'POJO' },
  { pattern: /\bcreate read update delete\b/gi, replacement: 'CRUD' },
  { pattern: /\bobject relational mapping\b/gi, replacement: 'ORM' },
  { pattern: /\bobject relational mapper\b/gi, replacement: 'ORM' },
  { pattern: /\brepresentational state transfer\b/gi, replacement: 'REST' },
  { pattern: /\bjson web token\b/gi, replacement: 'JWT' },
  { pattern: /\bopen authorization\b/gi, replacement: 'OAuth' },
  { pattern: /\bhypertext markup language\b/gi, replacement: 'HTML' },
  { pattern: /\bcascading style sheets\b/gi, replacement: 'CSS' },
  { pattern: /\bdocument object model\b/gi, replacement: 'DOM' },
  { pattern: /\bvirtual DOM\b/gi, replacement: 'VDOM' },
  { pattern: /\bserver side rendering\b/gi, replacement: 'SSR' },
  { pattern: /\bstatic site generation\b/gi, replacement: 'SSG' },
  { pattern: /\bclient side rendering\b/gi, replacement: 'CSR' },
  { pattern: /\bprogressive web app\b/gi, replacement: 'PWA' },
  { pattern: /\bsingle page application\b/gi, replacement: 'SPA' },
  { pattern: /\bmodel view controller\b/gi, replacement: 'MVC' },
  { pattern: /\bmodel view viewmodel\b/gi, replacement: 'MVVM' },
  { pattern: /\bdata transfer object\b/gi, replacement: 'DTO' },
  { pattern: /\bvalue object\b/gi, replacement: 'VO' },
  { pattern: /\bentity relationship diagram\b/gi, replacement: 'ERD' },
  { pattern: /\bunified modeling language\b/gi, replacement: 'UML' },
  { pattern: /\bstructured query language\b/gi, replacement: 'SQL' },
  { pattern: /\bnoSQL\b/gi, replacement: 'NoSQL' },
  { pattern: /\bnot only SQL\b/gi, replacement: 'NoSQL' },
  { pattern: /\bmemcached\b/gi, replacement: 'memcache' },
  { pattern: /\bmessage queue\b/gi, replacement: 'MQ' },
  { pattern: /\bmessage queues\b/gi, replacement: 'MQs' },
  { pattern: /\bpub sub\b/gi, replacement: 'pub/sub' },
  { pattern: /\bpublish subscribe\b/gi, replacement: 'pub/sub' },
  { pattern: /\bevent driven architecture\b/gi, replacement: 'EDA' },
  { pattern: /\bmicroservices architecture\b/gi, replacement: 'microservices' },
  { pattern: /\bservice oriented architecture\b/gi, replacement: 'SOA' },
  { pattern: /\bserverless computing\b/gi, replacement: 'serverless' },
  { pattern: /\bfunction as a service\b/gi, replacement: 'FaaS' },
  { pattern: /\bbackend as a service\b/gi, replacement: 'BaaS' },
  { pattern: /\bplatform as a service\b/gi, replacement: 'PaaS' },
];

export function abbreviationTransform(input: string) {
  return applyRules(input, 'abbreviation', 'low', RULES);
}
