import { applyRules } from './shared';

// Expand common word pairs into contractions.  Very safe for LLM context.
const RULES = [
  { pattern: /\bdo not\b/gi, replacement: "don't" },
  { pattern: /\bdoes not\b/gi, replacement: "doesn't" },
  { pattern: /\bdid not\b/gi, replacement: "didn't" },
  { pattern: /\bwill not\b/gi, replacement: "won't" },
  { pattern: /\bwould not\b/gi, replacement: "wouldn't" },
  { pattern: /\bshould not\b/gi, replacement: "shouldn't" },
  { pattern: /\bcould not\b/gi, replacement: "couldn't" },
  { pattern: /\bmight not\b/gi, replacement: "mightn't" },
  { pattern: /\bmust not\b/gi, replacement: "mustn't" },
  { pattern: /\bcan not\b/gi, replacement: "can't" },
  { pattern: /\bis not\b/gi, replacement: "isn't" },
  { pattern: /\bare not\b/gi, replacement: "aren't" },
  { pattern: /\bwas not\b/gi, replacement: "wasn't" },
  { pattern: /\bwere not\b/gi, replacement: "weren't" },
  { pattern: /\bhas not\b/gi, replacement: "hasn't" },
  { pattern: /\bhave not\b/gi, replacement: "haven't" },
  { pattern: /\bhad not\b/gi, replacement: "hadn't" },
  { pattern: /\bit is\b/gi, replacement: "it's" },
  { pattern: /\bit has\b/gi, replacement: "it's" },
  { pattern: /\bthat is\b/gi, replacement: "that's" },
  { pattern: /\bthat has\b/gi, replacement: "that's" },
  { pattern: /\bthere is\b/gi, replacement: "there's" },
  { pattern: /\bthere has\b/gi, replacement: "there's" },
  { pattern: /\bthere are\b/gi, replacement: "there're" },
  { pattern: /\bthey are\b/gi, replacement: "they're" },
  { pattern: /\bthey have\b/gi, replacement: "they've" },
  { pattern: /\bthey had\b/gi, replacement: "they'd" },
  { pattern: /\bwe are\b/gi, replacement: "we're" },
  { pattern: /\bwe have\b/gi, replacement: "we've" },
  { pattern: /\bwe had\b/gi, replacement: "we'd" },
  { pattern: /\bwe will\b/gi, replacement: "we'll" },
  { pattern: /\byou are\b/gi, replacement: "you're" },
  { pattern: /\byou have\b/gi, replacement: "you've" },
  { pattern: /\byou had\b/gi, replacement: "you'd" },
  { pattern: /\byou will\b/gi, replacement: "you'll" },
  { pattern: /\byou would\b/gi, replacement: "you'd" },
  { pattern: /\bhe is\b/gi, replacement: "he's" },
  { pattern: /\bhe has\b/gi, replacement: "he's" },
  { pattern: /\bhe will\b/gi, replacement: "he'll" },
  { pattern: /\bhe had\b/gi, replacement: "he'd" },
  { pattern: /\bshe is\b/gi, replacement: "she's" },
  { pattern: /\bshe has\b/gi, replacement: "she's" },
  { pattern: /\bshe will\b/gi, replacement: "she'll" },
  { pattern: /\bshe had\b/gi, replacement: "she'd" },
  { pattern: /\bI am\b/gi, replacement: "I'm" },
  { pattern: /\bI have\b/gi, replacement: "I've" },
  { pattern: /\bI had\b/gi, replacement: "I'd" },
  { pattern: /\bI will\b/gi, replacement: "I'll" },
  { pattern: /\bI would\b/gi, replacement: "I'd" },
  { pattern: /\blet us\b/gi, replacement: "let's" },
  { pattern: /\bis not\b/gi, replacement: "isn't" },
  { pattern: /\bare not\b/gi, replacement: "aren't" },
  { pattern: /\bwas not\b/gi, replacement: "wasn't" },
  { pattern: /\bwere not\b/gi, replacement: "weren't" },
];

export function contractionTransform(input: string) {
  return applyRules(input, 'contraction', 'low', RULES);
}
