import { applyRules } from './shared';

// Sorted longest-first to avoid partial matches.
// These are discourse markers, hedges, and conversational filler that carry
// little semantic signal for LLM context windows.
const RULES = [
  // Multi-word hedges / disclaimers (remove entirely)
  { pattern: /\bit is important to mention that\b/gi, replacement: '' },
  { pattern: /\bit should be noted that\b/gi, replacement: '' },
  { pattern: /\bit is worth noting that\b/gi, replacement: '' },
  { pattern: /\bit goes without saying that\b/gi, replacement: '' },
  { pattern: /\bneedless to say,?\b/gi, replacement: '' },
  { pattern: /\bneedless to mention,?\b/gi, replacement: '' },
  { pattern: /\bfor what it is worth,?\b/gi, replacement: '' },
  { pattern: /\bfor what it's worth,?\b/gi, replacement: '' },
  { pattern: /\bjust so you know,?\b/gi, replacement: '' },
  { pattern: /\bif you ask me,?\b/gi, replacement: '' },
  { pattern: /\bto tell you the truth,?\b/gi, replacement: '' },
  { pattern: /\bto be honest,?\b/gi, replacement: '' },
  { pattern: /\bto be perfectly honest,?\b/gi, replacement: '' },
  { pattern: /\bfrankly speaking,?\b/gi, replacement: '' },
  { pattern: /\bquite frankly,?\b/gi, replacement: '' },
  { pattern: /\bas a matter of fact,?\b/gi, replacement: '' },
  { pattern: /\bin my honest opinion,?\b/gi, replacement: '' },
  { pattern: /\bin my humble opinion,?\b/gi, replacement: '' },
  { pattern: /\bin my personal opinion,?\b/gi, replacement: '' },
  { pattern: /\bin my professional opinion,?\b/gi, replacement: '' },
  { pattern: /\bin my view,?\b/gi, replacement: '' },
  { pattern: /\bfrom my perspective,?\b/gi, replacement: '' },
  { pattern: /\bfrom my point of view,?\b/gi, replacement: '' },
  { pattern: /\bin my experience,?\b/gi, replacement: '' },
  { pattern: /\bin my understanding,?\b/gi, replacement: '' },
  { pattern: /\bas far as I know,?\b/gi, replacement: '' },
  { pattern: /\bas far as I am aware,?\b/gi, replacement: '' },
  { pattern: /\bas far as I'm aware,?\b/gi, replacement: '' },
  { pattern: /\bto the best of my knowledge,?\b/gi, replacement: '' },
  { pattern: /\bto the best of my understanding,?\b/gi, replacement: '' },
  { pattern: /\bI believe that\b/gi, replacement: '' },
  { pattern: /\bI think that\b/gi, replacement: '' },
  { pattern: /\bI feel that\b/gi, replacement: '' },
  { pattern: /\bI suppose that\b/gi, replacement: '' },
  { pattern: /\bI assume that\b/gi, replacement: '' },
  { pattern: /\bI would say that\b/gi, replacement: '' },
  { pattern: /\bI would argue that\b/gi, replacement: '' },
  { pattern: /\bI would suggest that\b/gi, replacement: '' },
  { pattern: /\bI would recommend that\b/gi, replacement: '' },
  { pattern: /\bit seems to me that\b/gi, replacement: '' },
  { pattern: /\bit appears to me that\b/gi, replacement: '' },
  { pattern: /\bit seems that\b/gi, replacement: '' },
  { pattern: /\bit appears that\b/gi, replacement: '' },
  { pattern: /\bit looks like\b/gi, replacement: '' },
  { pattern: /\bit looks as though\b/gi, replacement: '' },
  { pattern: /\bit would seem that\b/gi, replacement: '' },
  { pattern: /\bit is my understanding that\b/gi, replacement: '' },
  { pattern: /\bit is my belief that\b/gi, replacement: '' },
  { pattern: /\bas you probably know,?\b/gi, replacement: '' },
  { pattern: /\bas you may know,?\b/gi, replacement: '' },
  { pattern: /\bas you know,?\b/gi, replacement: '' },
  { pattern: /\bas you are aware,?\b/gi, replacement: '' },
  { pattern: /\bas we all know,?\b/gi, replacement: '' },
  { pattern: /\bat the end of the day,?\b/gi, replacement: '' },
  { pattern: /\ball things considered,?\b/gi, replacement: '' },
  { pattern: /\ball in all,?\b/gi, replacement: '' },
  { pattern: /\bwhen all is said and done,?\b/gi, replacement: '' },
  { pattern: /\bin the final analysis,?\b/gi, replacement: '' },
  { pattern: /\bin the last analysis,?\b/gi, replacement: '' },
  { pattern: /\bin the grand scheme of things,?\b/gi, replacement: '' },
  { pattern: /\bin the bigger picture,?\b/gi, replacement: '' },
  { pattern: /\bon the whole,?\b/gi, replacement: '' },
  { pattern: /\bby and large,?\b/gi, replacement: '' },
  { pattern: /\bfor the most part,?\b/gi, replacement: '' },
  { pattern: /\bin most cases,?\b/gi, replacement: '' },
  { pattern: /\bin many cases,?\b/gi, replacement: '' },
  { pattern: /\bin some cases,?\b/gi, replacement: '' },
  { pattern: /\bin general,?\b/gi, replacement: '' },
  { pattern: /\bgenerally speaking,?\b/gi, replacement: '' },
  { pattern: /\bmore often than not,?\b/gi, replacement: '' },
  { pattern: /\bmost of the time,?\b/gi, replacement: '' },
  { pattern: /\bas a general rule,?\b/gi, replacement: '' },
  { pattern: /\bin most instances,?\b/gi, replacement: '' },
  { pattern: /\bas a rule,?\b/gi, replacement: '' },
  { pattern: /\bin essence,?\b/gi, replacement: '' },
  { pattern: /\bat its core,?\b/gi, replacement: '' },
  { pattern: /\bwhen you get right down to it,?\b/gi, replacement: '' },

  // Single-word hedges (remove entirely)
  { pattern: /\bbasically,?\b/gi, replacement: '' },
  { pattern: /\bliterally,?\b/gi, replacement: '' },
  { pattern: /\bhonestly,?\b/gi, replacement: '' },
  { pattern: /\bsimply put,?\b/gi, replacement: '' },
  { pattern: /\bput simply,?\b/gi, replacement: '' },
  { pattern: /\bin short,?\b/gi, replacement: '' },
  { pattern: /\bin brief,?\b/gi, replacement: '' },
  { pattern: /\bin summary,?\b/gi, replacement: '' },
  { pattern: /\bin a nutshell,?\b/gi, replacement: '' },
  { pattern: /\bto sum up,?\b/gi, replacement: '' },
  { pattern: /\bto summarize,?\b/gi, replacement: '' },
  { pattern: /\bto recap,?\b/gi, replacement: '' },
  { pattern: /\bso to speak,?\b/gi, replacement: '' },
  { pattern: /\bif you will,?\b/gi, replacement: '' },
  { pattern: /\bif you like,?\b/gi, replacement: '' },
  { pattern: /\bkind of,?\b/gi, replacement: '' },
  { pattern: /\bsort of,?\b/gi, replacement: '' },
  { pattern: /\bmore or less,?\b/gi, replacement: '' },
  { pattern: /\bin a way,?\b/gi, replacement: '' },
  { pattern: /\bin a sense,?\b/gi, replacement: '' },
  { pattern: /\bin some ways,?\b/gi, replacement: '' },
  { pattern: /\bin some sense,?\b/gi, replacement: '' },
  { pattern: /\bto some extent,?\b/gi, replacement: '' },
  { pattern: /\bto a certain extent,?\b/gi, replacement: '' },
  { pattern: /\bto a large extent,?\b/gi, replacement: '' },
  { pattern: /\bto a degree,?\b/gi, replacement: '' },
  { pattern: /\barguably,?\b/gi, replacement: '' },
  { pattern: /\bpresumably,?\b/gi, replacement: '' },
  { pattern: /\bapparently,?\b/gi, replacement: '' },
  { pattern: /\bobviously,?\b/gi, replacement: '' },
  { pattern: /\bclearly,?\b/gi, replacement: '' },
  { pattern: /\bundoubtedly,?\b/gi, replacement: '' },
  { pattern: /\bcertainly,?\b/gi, replacement: '' },
  { pattern: /\bdefinitely,?\b/gi, replacement: '' },
  { pattern: /\babsolutely,?\b/gi, replacement: '' },
  { pattern: /\bessentially,?\b/gi, replacement: '' },
  { pattern: /\bfundamentally,?\b/gi, replacement: '' },
  { pattern: /\bpractically speaking,?\b/gi, replacement: '' },
  { pattern: /\bfor all intents and purposes,?\b/gi, replacement: '' },
  { pattern: /\bwith that said,?\b/gi, replacement: '' },
  { pattern: /\bthat said,?\b/gi, replacement: '' },
  { pattern: /\bhaving said that,?\b/gi, replacement: '' },
  { pattern: /\bwith that in mind,?\b/gi, replacement: '' },
  { pattern: /\bbearing that in mind,?\b/gi, replacement: '' },
  { pattern: /\bkeeping that in mind,?\b/gi, replacement: '' },
  { pattern: /\bon a related note,?\b/gi, replacement: '' },
  { pattern: /\bon another note,?\b/gi, replacement: '' },
  { pattern: /\bspeaking of which,?\b/gi, replacement: '' },
  { pattern: /\bwhich brings me to\b/gi, replacement: '' },
  { pattern: /\bwhich reminds me,?\b/gi, replacement: '' },
  { pattern: /\bincidentally,?\b/gi, replacement: '' },
  { pattern: /\bby the way,?\b/gi, replacement: '' },
  { pattern: /\bBTW,?\b/gi, replacement: '' },
  { pattern: /\bFYI,?\b/gi, replacement: '' },
  { pattern: /\bfor your information,?\b/gi, replacement: '' },
  { pattern: /\bplease note,?\b/gi, replacement: '' },
  { pattern: /\bplease be aware,?\b/gi, replacement: '' },
  { pattern: /\bplease keep in mind,?\b/gi, replacement: '' },
  { pattern: /\bit is worth mentioning,?\b/gi, replacement: '' },
  { pattern: /\bI wanted to let you know,?\b/gi, replacement: '' },
  { pattern: /\bI just wanted to say,?\b/gi, replacement: '' },
  { pattern: /\bI just wanted to mention,?\b/gi, replacement: '' },
  { pattern: /\bI wanted to mention,?\b/gi, replacement: '' },
  { pattern: /\bI should mention,?\b/gi, replacement: '' },
  { pattern: /\bI should note,?\b/gi, replacement: '' },
  { pattern: /\bI should point out,?\b/gi, replacement: '' },
  { pattern: /\bI want to point out,?\b/gi, replacement: '' },
  { pattern: /\bit must be said,?\b/gi, replacement: '' },
  { pattern: /\bit bears mentioning,?\b/gi, replacement: '' },
  { pattern: /\bit bears repeating,?\b/gi, replacement: '' },

  // Redundant intensifiers (remove entirely)
  { pattern: /\bvery much,?\b/gi, replacement: '' },
  { pattern: /\breally very,?\b/gi, replacement: '' },
  { pattern: /\bquite very,?\b/gi, replacement: '' },
  { pattern: /\bpretty much,?\b/gi, replacement: '' },
  { pattern: /\bfairly well,?\b/gi, replacement: '' },
  { pattern: /\bmore or less,?\b/gi, replacement: '' },

  // Transitionals that can often be dropped in technical context
  { pattern: /\bnow then,?\b/gi, replacement: '' },
  { pattern: /\bso then,?\b/gi, replacement: '' },
  { pattern: /\bwell then,?\b/gi, replacement: '' },
  { pattern: /\bokay then,?\b/gi, replacement: '' },
  { pattern: /\balright then,?\b/gi, replacement: '' },
  { pattern: /\bright then,?\b/gi, replacement: '' },
  { pattern: /\banyway,?\b/gi, replacement: '' },
  { pattern: /\banyhow,?\b/gi, replacement: '' },
  { pattern: /\banyways,?\b/gi, replacement: '' },
  { pattern: /\bnevertheless,?\b/gi, replacement: '' },
  { pattern: /\bnonetheless,?\b/gi, replacement: '' },
  { pattern: /\bnotwithstanding,?\b/gi, replacement: '' },
  { pattern: /\bmeanwhile,?\b/gi, replacement: '' },
  { pattern: /\bmeantime,?\b/gi, replacement: '' },
  { pattern: /\bwhereas,?\b/gi, replacement: '' },
  { pattern: /\bwhile it is true that,?\b/gi, replacement: '' },
  { pattern: /\bthat being said,?\b/gi, replacement: '' },
  { pattern: /\bwith all due respect,?\b/gi, replacement: '' },

  // Politeness filler (remove)
  { pattern: /\bplease,?\b/gi, replacement: '' },
  { pattern: /\bkindly,?\b/gi, replacement: '' },
  { pattern: /\bif you don't mind,?\b/gi, replacement: '' },
  { pattern: /\bif you wouldn't mind,?\b/gi, replacement: '' },
  { pattern: /\bwould you mind,?\b/gi, replacement: '' },
  { pattern: /\bcould you please,?\b/gi, replacement: '' },
  { pattern: /\bwould you please,?\b/gi, replacement: '' },
  { pattern: /\bwould you be so kind as to,?\b/gi, replacement: '' },
  { pattern: /\bI would appreciate it if you could,?\b/gi, replacement: '' },
  { pattern: /\bI would be grateful if you could,?\b/gi, replacement: '' },
  { pattern: /\bit would be great if you could,?\b/gi, replacement: '' },
  { pattern: /\bit would be appreciated if you could,?\b/gi, replacement: '' },
  { pattern: /\bwould it be possible for you to,?\b/gi, replacement: '' },
  { pattern: /\bwould it be possible to,?\b/gi, replacement: '' },
  { pattern: /\bis it possible to,?\b/gi, replacement: '' },
  { pattern: /\bis it possible for you to,?\b/gi, replacement: '' },
  { pattern: /\bcan you possibly,?\b/gi, replacement: '' },
  { pattern: /\bcould you possibly,?\b/gi, replacement: '' },
  { pattern: /\bif possible,?\b/gi, replacement: '' },
  { pattern: /\bwhenever possible,?\b/gi, replacement: '' },
  { pattern: /\bwherever possible,?\b/gi, replacement: '' },
  { pattern: /\bif at all possible,?\b/gi, replacement: '' },

  // Gratitude / social filler
  { pattern: /\bthanks in advance,?\b/gi, replacement: '' },
  { pattern: /\bthank you in advance,?\b/gi, replacement: '' },
  { pattern: /\bmany thanks in advance,?\b/gi, replacement: '' },
  { pattern: /\bI appreciate your help,?\b/gi, replacement: '' },
  { pattern: /\bI would appreciate your help,?\b/gi, replacement: '' },
  { pattern: /\bI appreciate your assistance,?\b/gi, replacement: '' },
  { pattern: /\bI appreciate your time,?\b/gi, replacement: '' },
  { pattern: /\bthanks for your time,?\b/gi, replacement: '' },
  { pattern: /\bthanks for your help,?\b/gi, replacement: '' },
  { pattern: /\bthanks for your patience,?\b/gi, replacement: '' },
  { pattern: /\bthank you for your patience,?\b/gi, replacement: '' },
  { pattern: /\bthank you for your understanding,?\b/gi, replacement: '' },
  { pattern: /\bthank you for reaching out,?\b/gi, replacement: '' },
  { pattern: /\bthank you for getting in touch,?\b/gi, replacement: '' },
  { pattern: /\bthank you for contacting us,?\b/gi, replacement: '' },
  { pattern: /\bthank you for your email,?\b/gi, replacement: '' },
  { pattern: /\bthank you for your message,?\b/gi, replacement: '' },
  { pattern: /\bI hope this helps,?\b/gi, replacement: '' },
  { pattern: /\bI hope that helps,?\b/gi, replacement: '' },
  { pattern: /\bI hope you find this helpful,?\b/gi, replacement: '' },
  { pattern: /\bI hope everything is well,?\b/gi, replacement: '' },
  { pattern: /\bI hope you are doing well,?\b/gi, replacement: '' },
  { pattern: /\bI hope you are well,?\b/gi, replacement: '' },
  { pattern: /\bI hope all is well,?\b/gi, replacement: '' },
  { pattern: /\bI hope this email finds you well,?\b/gi, replacement: '' },
  { pattern: /\bI hope you're having a great day,?\b/gi, replacement: '' },
  { pattern: /\bI trust this finds you well,?\b/gi, replacement: '' },
  { pattern: /\bI trust you are well,?\b/gi, replacement: '' },
  { pattern: /\bI trust all is well,?\b/gi, replacement: '' },
  { pattern: /\bdon't hesitate to reach out,?\b/gi, replacement: '' },
  { pattern: /\bplease don't hesitate to contact me,?\b/gi, replacement: '' },
  { pattern: /\bplease feel free to reach out,?\b/gi, replacement: '' },
  { pattern: /\bfeel free to reach out,?\b/gi, replacement: '' },
  { pattern: /\blet me know if you have any questions,?\b/gi, replacement: '' },
  { pattern: /\bplease let me know if you have any questions,?\b/gi, replacement: '' },
  { pattern: /\bplease let me know if you need anything else,?\b/gi, replacement: '' },
  { pattern: /\blet me know if you need anything else,?\b/gi, replacement: '' },
  { pattern: /\bif you have any questions,?\b/gi, replacement: '' },
  { pattern: /\bif you have any further questions,?\b/gi, replacement: '' },
  { pattern: /\bif you need any further information,?\b/gi, replacement: '' },
  { pattern: /\bif you need anything else,?\b/gi, replacement: '' },
  { pattern: /\bshould you have any questions,?\b/gi, replacement: '' },
  { pattern: /\bshould you need any further information,?\b/gi, replacement: '' },
  { pattern: /\bplease do not hesitate to,?\b/gi, replacement: '' },
  { pattern: /\bdo not hesitate to,?\b/gi, replacement: '' },
  { pattern: /\bfeel free to ask,?\b/gi, replacement: '' },
  { pattern: /\bfeel free to let me know,?\b/gi, replacement: '' },

  // Softeners (remove)
  { pattern: /\bI just wanted to\b/gi, replacement: '' },
  { pattern: /\bI was just wondering\b/gi, replacement: '' },
  { pattern: /\bI was wondering\b/gi, replacement: '' },
  { pattern: /\bI was thinking\b/gi, replacement: '' },
  { pattern: /\bI was hoping\b/gi, replacement: '' },
  { pattern: /\bI wanted to ask\b/gi, replacement: '' },
  { pattern: /\bI wanted to check\b/gi, replacement: '' },
  { pattern: /\bI wanted to see\b/gi, replacement: '' },
  { pattern: /\bI wanted to know\b/gi, replacement: '' },
  { pattern: /\bI wanted to find out\b/gi, replacement: '' },
  { pattern: /\bI was wondering if\b/gi, replacement: '' },
  { pattern: /\bI was wondering whether\b/gi, replacement: '' },
  { pattern: /\bI wanted to know if\b/gi, replacement: '' },
  { pattern: /\bI wanted to know whether\b/gi, replacement: '' },
  { pattern: /\bI was hoping to\b/gi, replacement: '' },
  { pattern: /\bI was hoping that\b/gi, replacement: '' },

  // Greetings / closings
  { pattern: /\bhi there,?\b/gi, replacement: '' },
  { pattern: /\bhey there,?\b/gi, replacement: '' },
  { pattern: /\bhello there,?\b/gi, replacement: '' },
  { pattern: /\bgreetings,?\b/gi, replacement: '' },
  { pattern: /\bgood morning,?\b/gi, replacement: '' },
  { pattern: /\bgood afternoon,?\b/gi, replacement: '' },
  { pattern: /\bgood evening,?\b/gi, replacement: '' },
  { pattern: /\bgood day,?\b/gi, replacement: '' },
  { pattern: /\bdear sir or madam,?\b/gi, replacement: '' },
  { pattern: /\bto whom it may concern,?\b/gi, replacement: '' },
  { pattern: /\bbest regards,?\b/gi, replacement: '' },
  { pattern: /\bkind regards,?\b/gi, replacement: '' },
  { pattern: /\bwarm regards,?\b/gi, replacement: '' },
  { pattern: /\bregards,?\b/gi, replacement: '' },
  { pattern: /\bbest wishes,?\b/gi, replacement: '' },
  { pattern: /\bwarm wishes,?\b/gi, replacement: '' },
  { pattern: /\byours sincerely,?\b/gi, replacement: '' },
  { pattern: /\byours truly,?\b/gi, replacement: '' },
  { pattern: /\byours faithfully,?\b/gi, replacement: '' },
  { pattern: /\bsincerely,?\b/gi, replacement: '' },
  { pattern: /\bcheers,?\b/gi, replacement: '' },
  { pattern: /\btake care,?\b/gi, replacement: '' },
  { pattern: /\bhave a great day,?\b/gi, replacement: '' },
  { pattern: /\bhave a good one,?\b/gi, replacement: '' },
  { pattern: /\ball the best,?\b/gi, replacement: '' },
  { pattern: /\bspeak soon,?\b/gi, replacement: '' },
  { pattern: /\btalk soon,?\b/gi, replacement: '' },
  { pattern: /\blooking forward to hearing from you,?\b/gi, replacement: '' },
  { pattern: /\bI look forward to hearing from you,?\b/gi, replacement: '' },
  { pattern: /\bI am looking forward to hearing from you,?\b/gi, replacement: '' },
  { pattern: /\blooking forward to your reply,?\b/gi, replacement: '' },
  { pattern: /\bI look forward to your reply,?\b/gi, replacement: '' },
  { pattern: /\bI look forward to working with you,?\b/gi, replacement: '' },
  { pattern: /\blooking forward to working with you,?\b/gi, replacement: '' },
  { pattern: /\blooking forward to it,?\b/gi, replacement: '' },

  // Doubles / uncertainty hedges
  { pattern: /\bI am not sure,?\b/gi, replacement: '' },
  { pattern: /\bI'm not sure,?\b/gi, replacement: '' },
  { pattern: /\bI do not know,?\b/gi, replacement: '' },
  { pattern: /\bI don't know,?\b/gi, replacement: '' },
  { pattern: /\bI have no idea,?\b/gi, replacement: '' },
  { pattern: /\bI haven't a clue,?\b/gi, replacement: '' },
  { pattern: /\bit is unclear,?\b/gi, replacement: '' },
  { pattern: /\bit is not clear,?\b/gi, replacement: '' },
  { pattern: /\bit is not entirely clear,?\b/gi, replacement: '' },
  { pattern: /\bit remains to be seen,?\b/gi, replacement: '' },
  { pattern: /\bonly time will tell,?\b/gi, replacement: '' },
  { pattern: /\bwe will have to wait and see,?\b/gi, replacement: '' },
  { pattern: /\bit is too early to say,?\b/gi, replacement: '' },
  { pattern: /\bit is difficult to say,?\b/gi, replacement: '' },
  { pattern: /\bit is hard to say,?\b/gi, replacement: '' },
];

export function fillerRemoval(input: string) {
  return applyRules(input, 'filler-removal', 'medium', RULES);
}
