import { applyRules, type Rule } from './shared';

const COMMON: Rule[] = [
  // Causal / reasoning
  { pattern: /\bdue to the fact that\b/gi, replacement: 'because' },
  { pattern: /\bfor the reason that\b/gi, replacement: 'because' },
  { pattern: /\bby virtue of the fact that\b/gi, replacement: 'because' },
  { pattern: /\bon account of the fact that\b/gi, replacement: 'because' },
  { pattern: /\bon account of\b/gi, replacement: 'because' },
  { pattern: /\bowing to the fact that\b/gi, replacement: 'because' },
  { pattern: /\bthe reason is that\b/gi, replacement: 'because' },
  { pattern: /\bthis is because\b/gi, replacement: 'because' },
  { pattern: /\bthe reason why\b/gi, replacement: 'because' },
  { pattern: /\bfor this reason\b/gi, replacement: 'so' },
  { pattern: /\bas a consequence\b/gi, replacement: 'so' },
  { pattern: /\bas a result\b/gi, replacement: 'so' },
  { pattern: /\bconsequently\b/gi, replacement: 'so' },
  { pattern: /\btherefore\b/gi, replacement: 'so' },
  { pattern: /\bthus\b/gi, replacement: 'so' },
  { pattern: /\bhence\b/gi, replacement: 'so' },
  { pattern: /\bin consequence\b/gi, replacement: 'so' },
  { pattern: /\bthat being the case\b/gi, replacement: 'so' },
  { pattern: /\bgiven that\b/gi, replacement: 'since' },
  { pattern: /\bconsidering that\b/gi, replacement: 'since' },
  { pattern: /\bin light of\b/gi, replacement: 'given' },
  { pattern: /\bin view of\b/gi, replacement: 'given' },
  // Conditional
  { pattern: /\bin the event that\b/gi, replacement: 'if' },
  { pattern: /\bin the case that\b/gi, replacement: 'if' },
  { pattern: /\bin a situation where\b/gi, replacement: 'if' },
  { pattern: /\bprovided that\b/gi, replacement: 'if' },
  { pattern: /\bassuming that\b/gi, replacement: 'if' },
  { pattern: /\bon condition that\b/gi, replacement: 'if' },
  { pattern: /\bregardless of the fact that\b/gi, replacement: 'although' },
  { pattern: /\bin spite of the fact that\b/gi, replacement: 'although' },
  { pattern: /\bdespite the fact that\b/gi, replacement: 'although' },
  { pattern: /\beven though\b/gi, replacement: 'although' },
  { pattern: /\bno matter how\b/gi, replacement: 'although' },
  // Temporal
  { pattern: /\bat this point in time\b/gi, replacement: 'now' },
  { pattern: /\bat the present time\b/gi, replacement: 'now' },
  { pattern: /\bfrom this point forward\b/gi, replacement: 'then' },
  { pattern: /\bfrom now on\b/gi, replacement: 'then' },
  { pattern: /\bgoing forward\b/gi, replacement: 'then' },
  { pattern: /\bfor the time being\b/gi, replacement: 'temporarily' },
  { pattern: /\bfrom time to time\b/gi, replacement: 'occasionally' },
  { pattern: /\bonce in a while\b/gi, replacement: 'occasionally' },
  { pattern: /\bprior to\b/gi, replacement: 'before' },
  { pattern: /\bsubsequent to\b/gi, replacement: 'after' },
  { pattern: /\bduring the course of\b/gi, replacement: 'during' },
  { pattern: /\bin the course of\b/gi, replacement: 'during' },
  { pattern: /\bover the course of\b/gi, replacement: 'during' },
  { pattern: /\bthroughout the course of\b/gi, replacement: 'during' },
  { pattern: /\bin the process of\b/gi, replacement: 'during' },
  { pattern: /\bnevertheless\b/gi, replacement: 'yet' },
  { pattern: /\bnonetheless\b/gi, replacement: 'yet' },
  { pattern: /\bnotwithstanding\b/gi, replacement: 'yet' },
  { pattern: /\beven so\b/gi, replacement: 'yet' },
  // Purpose / intent
  { pattern: /\bin order to\b/gi, replacement: 'to' },
  { pattern: /\bin an effort to\b/gi, replacement: 'to' },
  { pattern: /\bin an attempt to\b/gi, replacement: 'to' },
  { pattern: /\bwith a view to\b/gi, replacement: 'to' },
  { pattern: /\bfor the purpose of\b/gi, replacement: 'to' },
  { pattern: /\bwith the aim of\b/gi, replacement: 'to' },
  { pattern: /\bwith the intention of\b/gi, replacement: 'to' },
  { pattern: /\bwith the objective of\b/gi, replacement: 'to' },
  { pattern: /\bwith the goal of\b/gi, replacement: 'to' },
  { pattern: /\bso as to\b/gi, replacement: 'to' },
  { pattern: /\bfor the sake of\b/gi, replacement: 'for' },
  // About / regarding
  { pattern: /\bwith regard to\b/gi, replacement: 'about' },
  { pattern: /\bwith respect to\b/gi, replacement: 'about' },
  { pattern: /\bwith reference to\b/gi, replacement: 'about' },
  { pattern: /\bin regard to\b/gi, replacement: 'about' },
  { pattern: /\bin respect to\b/gi, replacement: 'about' },
  { pattern: /\bin relation to\b/gi, replacement: 'about' },
  { pattern: /\bpertaining to\b/gi, replacement: 'about' },
  { pattern: /\brelating to\b/gi, replacement: 'about' },
  { pattern: /\bconcerning\b/gi, replacement: 'about' },
  { pattern: /\bregarding\b/gi, replacement: 'about' },
  // Proximity
  { pattern: /\bin close proximity to\b/gi, replacement: 'near' },
  { pattern: /\bin the vicinity of\b/gi, replacement: 'near' },
  { pattern: /\bin the neighborhood of\b/gi, replacement: 'near' },
  // Ability / possibility
  { pattern: /\bhas the ability to\b/gi, replacement: 'can' },
  { pattern: /\bhave the ability to\b/gi, replacement: 'can' },
  { pattern: /\bis able to\b/gi, replacement: 'can' },
  { pattern: /\bare able to\b/gi, replacement: 'can' },
  { pattern: /\bwas able to\b/gi, replacement: 'could' },
  { pattern: /\bwere able to\b/gi, replacement: 'could' },
  { pattern: /\bwill be able to\b/gi, replacement: 'can' },
  { pattern: /\bwould be able to\b/gi, replacement: 'could' },
  { pattern: /\bis capable of\b/gi, replacement: 'can' },
  { pattern: /\bis not able to\b/gi, replacement: 'cannot' },
  { pattern: /\bare not able to\b/gi, replacement: 'cannot' },
  { pattern: /\bit is necessary that\b/gi, replacement: 'must' },
  { pattern: /\bit is essential that\b/gi, replacement: 'must' },
  { pattern: /\bit is vital that\b/gi, replacement: 'must' },
  { pattern: /\bit is critical that\b/gi, replacement: 'must' },
  { pattern: /\bit is crucial that\b/gi, replacement: 'must' },
  { pattern: /\bit is imperative that\b/gi, replacement: 'must' },
  { pattern: /\bit is required that\b/gi, replacement: 'must' },
  { pattern: /\bit is mandatory that\b/gi, replacement: 'must' },
  { pattern: /\bit is important that\b/gi, replacement: 'must' },
  { pattern: /\bit is advisable that\b/gi, replacement: 'should' },
  { pattern: /\bit is recommended that\b/gi, replacement: 'should' },
  { pattern: /\bit is suggested that\b/gi, replacement: 'should' },
  { pattern: /\bit would be best to\b/gi, replacement: 'should' },
  { pattern: /\bit is possible to\b/gi, replacement: 'can' },
  { pattern: /\bit is feasible to\b/gi, replacement: 'can' },
  { pattern: /\bit is unlikely that\b/gi, replacement: 'probably not' },
  { pattern: /\bit is likely that\b/gi, replacement: 'probably' },
  { pattern: /\bit is possible that\b/gi, replacement: 'maybe' },
  // Notes / observations
  { pattern: /\bit is worth pointing out that\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to note that\b/gi, replacement: 'note:' },
  { pattern: /\bit should be pointed out that\b/gi, replacement: 'note:' },
  { pattern: /\bit should be emphasized that\b/gi, replacement: 'note:' },
  { pattern: /\bit is clear that\b/gi, replacement: 'clearly' },
  { pattern: /\bit is obvious that\b/gi, replacement: 'clearly' },
  { pattern: /\bit is evident that\b/gi, replacement: 'clearly' },
  { pattern: /\bit is apparent that\b/gi, replacement: 'clearly' },
  { pattern: /\bthere is no doubt that\b/gi, replacement: 'clearly' },
  { pattern: /\bthere can be no doubt that\b/gi, replacement: 'clearly' },
  // Summaries
  { pattern: /\bin conclusion\b/gi, replacement: 'so' },
  { pattern: /\bin closing\b/gi, replacement: 'so' },
  { pattern: /\bin summation\b/gi, replacement: 'so' },
  { pattern: /\bin the end\b/gi, replacement: 'so' },
  { pattern: /\bat the end of the day\b/gi, replacement: 'so' },
  { pattern: /\bin the final analysis\b/gi, replacement: 'so' },
  { pattern: /\ball in all\b/gi, replacement: 'overall' },
  { pattern: /\ball things considered\b/gi, replacement: 'overall' },
  { pattern: /\bon balance\b/gi, replacement: 'overall' },
  // Examples
  { pattern: /\bfor example\b/gi, replacement: 'e.g.' },
  { pattern: /\bfor instance\b/gi, replacement: 'e.g.' },
  { pattern: /\bby way of example\b/gi, replacement: 'e.g.' },
  { pattern: /\bsuch as\b/gi, replacement: 'e.g.' },
  { pattern: /\bincluding but not limited to\b/gi, replacement: 'e.g.' },
  { pattern: /\band so on\b/gi, replacement: 'etc.' },
  { pattern: /\band so forth\b/gi, replacement: 'etc.' },
  { pattern: /\band the like\b/gi, replacement: 'etc.' },
  { pattern: /\bin other words\b/gi, replacement: 'i.e.' },
  { pattern: /\bthat is to say\b/gi, replacement: 'i.e.' },
  { pattern: /\bthat is,?\b/gi, replacement: 'i.e.' },
  { pattern: /\bnamely,?\b/gi, replacement: 'i.e.' },
  // Additions
  { pattern: /\bin addition\b/gi, replacement: 'also' },
  { pattern: /\bfurthermore\b/gi, replacement: 'also' },
  { pattern: /\bmoreover\b/gi, replacement: 'also' },
  { pattern: /\bwhat is more\b/gi, replacement: 'also' },
  { pattern: /\bon top of that\b/gi, replacement: 'also' },
  { pattern: /\bbesides,?\b/gi, replacement: 'also' },
  // Contrast
  { pattern: /\bon the other hand\b/gi, replacement: 'but' },
  { pattern: /\bon the contrary\b/gi, replacement: 'but' },
  { pattern: /\bconversely,?\b/gi, replacement: 'but' },
  { pattern: /\bin contrast,?\b/gi, replacement: 'but' },
  { pattern: /\bby contrast,?\b/gi, replacement: 'but' },
  { pattern: /\bcompared with\b/gi, replacement: 'vs' },
  { pattern: /\bcompared to\b/gi, replacement: 'vs' },
  { pattern: /\bin comparison with\b/gi, replacement: 'vs' },
  { pattern: /\bin comparison to\b/gi, replacement: 'vs' },
  // Sequence
  { pattern: /\bfirst and foremost\b/gi, replacement: 'first' },
  { pattern: /\bfirst of all\b/gi, replacement: 'first' },
  { pattern: /\bto begin with\b/gi, replacement: 'first' },
  { pattern: /\bto start with\b/gi, replacement: 'first' },
  { pattern: /\bfor a start\b/gi, replacement: 'first' },
  { pattern: /\bin the first place\b/gi, replacement: 'first' },
  { pattern: /\bsecondly\b/gi, replacement: 'second' },
  { pattern: /\bthirdly\b/gi, replacement: 'third' },
  { pattern: /\blast but not least\b/gi, replacement: 'finally' },
  { pattern: /\blast of all\b/gi, replacement: 'finally' },
  // Frequency / extent
  { pattern: /\bmore often than not\b/gi, replacement: 'usually' },
  { pattern: /\bfor the most part\b/gi, replacement: 'mostly' },
  { pattern: /\bby and large\b/gi, replacement: 'mostly' },
  { pattern: /\bon the whole\b/gi, replacement: 'mostly' },
  { pattern: /\bto a large extent\b/gi, replacement: 'mostly' },
  { pattern: /\bto some extent\b/gi, replacement: 'partly' },
  { pattern: /\bto a certain extent\b/gi, replacement: 'partly' },
  { pattern: /\bin part\b/gi, replacement: 'partly' },
  // General
  { pattern: /\bin general terms\b/gi, replacement: 'generally' },
  { pattern: /\bbroadly speaking\b/gi, replacement: 'generally' },
  { pattern: /\bas a general rule\b/gi, replacement: 'generally' },
  { pattern: /\bas a rule\b/gi, replacement: 'generally' },
  { pattern: /\bin most instances\b/gi, replacement: 'usually' },
  { pattern: /\bin most cases\b/gi, replacement: 'usually' },
  // Meaning / point
  { pattern: /\bthe point is that\b/gi, replacement: '' },
  { pattern: /\bthe fact of the matter is\b/gi, replacement: '' },
  { pattern: /\bthe fact is that\b/gi, replacement: '' },
  { pattern: /\bthe truth is that\b/gi, replacement: '' },
  { pattern: /\bthe reality is that\b/gi, replacement: '' },
  { pattern: /\bthe bottom line is\b/gi, replacement: '' },
  { pattern: /\bthe upshot is\b/gi, replacement: 'so' },
  { pattern: /\bthe result is\b/gi, replacement: 'so' },
  { pattern: /\bthe end result is\b/gi, replacement: 'so' },
  { pattern: /\bthis means that\b/gi, replacement: 'so' },
  { pattern: /\bthis implies that\b/gi, replacement: 'so' },
  { pattern: /\bthis suggests that\b/gi, replacement: 'so' },
  { pattern: /\bthis indicates that\b/gi, replacement: 'so' },
  { pattern: /\bthis shows that\b/gi, replacement: 'so' },
  { pattern: /\bthis demonstrates that\b/gi, replacement: 'so' },
  { pattern: /\bthis proves that\b/gi, replacement: 'so' },
  // Instead of / rather than
  { pattern: /\bras opposed to\b/gi, replacement: 'instead of' },
  { pattern: /\bas an alternative to\b/gi, replacement: 'instead of' },
  { pattern: /\bin place of\b/gi, replacement: 'instead of' },
  { pattern: /\bin lieu of\b/gi, replacement: 'instead of' },
  // Specifically
  { pattern: /\bin particular\b/gi, replacement: 'specifically' },
  { pattern: /\bmore specifically\b/gi, replacement: 'specifically' },
  { pattern: /\bto be specific\b/gi, replacement: 'specifically' },
  { pattern: /\bto be more specific\b/gi, replacement: 'specifically' },
  // Importance
  { pattern: /\babove all\b/gi, replacement: 'mainly' },
  { pattern: /\bmost importantly\b/gi, replacement: 'mainly' },
  { pattern: /\bmost significantly\b/gi, replacement: 'mainly' },
  { pattern: /\bmost notably\b/gi, replacement: 'mainly' },
  { pattern: /\bprincipally\b/gi, replacement: 'mainly' },
  { pattern: /\bchiefly\b/gi, replacement: 'mainly' },
  { pattern: /\bprimarily\b/gi, replacement: 'mainly' },
  // Caveats
  { pattern: /\bthat said\b/gi, replacement: 'but' },
  { pattern: /\bthat being said\b/gi, replacement: 'but' },
  { pattern: /\bhaving said that\b/gi, replacement: 'but' },
  { pattern: /\bwith that said\b/gi, replacement: 'but' },
  { pattern: /\bwith that in mind\b/gi, replacement: 'so' },
  { pattern: /\bwith this in mind\b/gi, replacement: 'so' },
  { pattern: /\bbearing that in mind\b/gi, replacement: 'so' },
  { pattern: /\bkeeping that in mind\b/gi, replacement: 'so' },
  { pattern: /\btaking this into account\b/gi, replacement: 'so' },
  { pattern: /\btaking that into account\b/gi, replacement: 'so' },
  { pattern: /\btaking this into consideration\b/gi, replacement: 'so' },
  { pattern: /\btaking that into consideration\b/gi, replacement: 'so' },
  { pattern: /\bin view of this\b/gi, replacement: 'so' },
  { pattern: /\bin view of that\b/gi, replacement: 'so' },
  { pattern: /\bin light of this\b/gi, replacement: 'so' },
  { pattern: /\bin light of that\b/gi, replacement: 'so' },
  { pattern: /\bunder the circumstances\b/gi, replacement: 'so' },
  { pattern: /\bunder these circumstances\b/gi, replacement: 'so' },
  { pattern: /\bunder those circumstances\b/gi, replacement: 'so' },
  { pattern: /\bgiven these circumstances\b/gi, replacement: 'so' },
  { pattern: /\bgiven those circumstances\b/gi, replacement: 'so' },
  { pattern: /\bwith this reservation\b/gi, replacement: 'but' },
  { pattern: /\bwith that reservation\b/gi, replacement: 'but' },
  { pattern: /\bwith this qualification\b/gi, replacement: 'but' },
  { pattern: /\bwith that qualification\b/gi, replacement: 'but' },
  { pattern: /\bwith this caveat\b/gi, replacement: 'but' },
  { pattern: /\bwith that caveat\b/gi, replacement: 'but' },
  { pattern: /\bapart from this\b/gi, replacement: 'but' },
  { pattern: /\bapart from that\b/gi, replacement: 'but' },
  { pattern: /\baside from this\b/gi, replacement: 'but' },
  { pattern: /\baside from that\b/gi, replacement: 'but' },
  { pattern: /\bexcept for this\b/gi, replacement: 'but' },
  { pattern: /\bexcept for that\b/gi, replacement: 'but' },
  { pattern: /\bother than this\b/gi, replacement: 'but' },
  { pattern: /\bother than that\b/gi, replacement: 'but' },
  // Misc
  { pattern: /\bin essence\b/gi, replacement: 'basically' },
  { pattern: /\bin actual fact\b/gi, replacement: 'actually' },
  { pattern: /\bin reality\b/gi, replacement: 'actually' },
  { pattern: /\bin effect\b/gi, replacement: 'effectively' },
  { pattern: /\bfor all practical purposes\b/gi, replacement: 'effectively' },
  { pattern: /\bto all intents and purposes\b/gi, replacement: 'effectively' },
  { pattern: /\bin practical terms\b/gi, replacement: 'practically' },
  { pattern: /\bat first glance\b/gi, replacement: 'initially' },
  { pattern: /\bon second thought\b/gi, replacement: 'reconsidering' },
  { pattern: /\bon reflection\b/gi, replacement: 'reconsidering' },
  { pattern: /\bon closer inspection\b/gi, replacement: 'inspecting' },
  { pattern: /\bupon closer examination\b/gi, replacement: 'examining' },
  { pattern: /\bon closer examination\b/gi, replacement: 'examining' },
  { pattern: /\ball things being equal\b/gi, replacement: 'normally' },
  { pattern: /\bother things being equal\b/gi, replacement: 'normally' },
  { pattern: /\beverything else being equal\b/gi, replacement: 'normally' },
  { pattern: /\ball else being equal\b/gi, replacement: 'normally' },
  { pattern: /\bin the same way\b/gi, replacement: 'likewise' },
  { pattern: /\bin a similar way\b/gi, replacement: 'likewise' },
  { pattern: /\bin a similar fashion\b/gi, replacement: 'likewise' },
  { pattern: /\bin a similar manner\b/gi, replacement: 'likewise' },
  { pattern: /\bsimilarly,?\b/gi, replacement: 'likewise' },
  { pattern: /\bfollowing on from\b/gi, replacement: 'after' },
  { pattern: /\bin the wake of\b/gi, replacement: 'after' },
  { pattern: /\bin the aftermath of\b/gi, replacement: 'after' },
  { pattern: /\bthereafter\b/gi, replacement: 'then' },
  { pattern: /\bhereafter\b/gi, replacement: 'then' },
  { pattern: /\bpreviously\b/gi, replacement: 'before' },
  { pattern: /\bheretofore\b/gi, replacement: 'before' },
  { pattern: /\bhitherto\b/gi, replacement: 'before' },
];

const AGENT_PROMPTS: Rule[] = [
  { pattern: /\bplease provide\b/gi, replacement: 'give' },
  { pattern: /\bcan you\b/gi, replacement: '' },
  { pattern: /\bI need you to\b/gi, replacement: '' },
  { pattern: /\bI want you to\b/gi, replacement: '' },
  { pattern: /\bI would like you to\b/gi, replacement: '' },
  { pattern: /\bwould you mind\b/gi, replacement: '' },
  { pattern: /\bcould you please\b/gi, replacement: '' },
  { pattern: /\bwould you please\b/gi, replacement: '' },
  { pattern: /\bwould you be so kind as to\b/gi, replacement: '' },
  { pattern: /\bit would be great if you could\b/gi, replacement: '' },
  { pattern: /\bit would be appreciated if you could\b/gi, replacement: '' },
  { pattern: /\bwould it be possible for you to\b/gi, replacement: '' },
  { pattern: /\bwould it be possible to\b/gi, replacement: '' },
  { pattern: /\bis it possible to\b/gi, replacement: '' },
  { pattern: /\bis it possible for you to\b/gi, replacement: '' },
];

const PROJECT_SPECS: Rule[] = [
  { pattern: /\bacceptance criteria\b/gi, replacement: 'criteria' },
  { pattern: /\bnon-functional requirements\b/gi, replacement: 'NFRs' },
  { pattern: /\bfunctional requirements\b/gi, replacement: 'FRs' },
  { pattern: /\buser story\b/gi, replacement: 'story' },
  { pattern: /\buser stories\b/gi, replacement: 'stories' },
  { pattern: /\buse case\b/gi, replacement: 'case' },
  { pattern: /\buse cases\b/gi, replacement: 'cases' },
  { pattern: /\bsuccess criteria\b/gi, replacement: 'criteria' },
  { pattern: /\bexit criteria\b/gi, replacement: 'criteria' },
  { pattern: /\bentry criteria\b/gi, replacement: 'criteria' },
  { pattern: /\bproject plan\b/gi, replacement: 'plan' },
  { pattern: /\bproject schedule\b/gi, replacement: 'schedule' },
  { pattern: /\bproject timeline\b/gi, replacement: 'timeline' },
  { pattern: /\bproject roadmap\b/gi, replacement: 'roadmap' },
  { pattern: /\bproject milestone\b/gi, replacement: 'milestone' },
  { pattern: /\bproject milestones\b/gi, replacement: 'milestones' },
  { pattern: /\bproject deliverable\b/gi, replacement: 'deliverable' },
  { pattern: /\bproject deliverables\b/gi, replacement: 'deliverables' },
  { pattern: /\bproject objective\b/gi, replacement: 'objective' },
  { pattern: /\bproject objectives\b/gi, replacement: 'objectives' },
  { pattern: /\bproject goal\b/gi, replacement: 'goal' },
  { pattern: /\bproject goals\b/gi, replacement: 'goals' },
  { pattern: /\bproject scope\b/gi, replacement: 'scope' },
  { pattern: /\bproject budget\b/gi, replacement: 'budget' },
  { pattern: /\bproject cost\b/gi, replacement: 'cost' },
  { pattern: /\bproject resource\b/gi, replacement: 'resource' },
  { pattern: /\bproject resources\b/gi, replacement: 'resources' },
  { pattern: /\bproject stakeholder\b/gi, replacement: 'stakeholder' },
  { pattern: /\bproject stakeholders\b/gi, replacement: 'stakeholders' },
  { pattern: /\bproject sponsor\b/gi, replacement: 'sponsor' },
  { pattern: /\bproject sponsors\b/gi, replacement: 'sponsors' },
  { pattern: /\bproject manager\b/gi, replacement: 'PM' },
  { pattern: /\bproject management\b/gi, replacement: 'PM' },
  { pattern: /\bproduct owner\b/gi, replacement: 'PO' },
  { pattern: /\bscrum master\b/gi, replacement: 'SM' },
  { pattern: /\bdevelopment team\b/gi, replacement: 'dev team' },
  { pattern: /\bqa team\b/gi, replacement: 'QA' },
  { pattern: /\bquality assurance\b/gi, replacement: 'QA' },
];

const DOCS_README: Rule[] = [
  { pattern: /\bfor the purpose of\b/gi, replacement: 'for' },
  { pattern: /\bin addition to\b/gi, replacement: 'and' },
  { pattern: /\bplease refer to\b/gi, replacement: 'see' },
  { pattern: /\bplease see\b/gi, replacement: 'see' },
  { pattern: /\bplease consult\b/gi, replacement: 'see' },
  { pattern: /\bplease check\b/gi, replacement: 'see' },
  { pattern: /\bplease review\b/gi, replacement: 'see' },
  { pattern: /\bplease read\b/gi, replacement: 'see' },
  { pattern: /\bplease visit\b/gi, replacement: 'see' },
  { pattern: /\bplease navigate to\b/gi, replacement: 'see' },
  { pattern: /\bplease go to\b/gi, replacement: 'see' },
  { pattern: /\bplease follow\b/gi, replacement: 'see' },
  { pattern: /\bplease use\b/gi, replacement: 'use' },
  { pattern: /\bplease try\b/gi, replacement: 'try' },
  { pattern: /\bplease ensure\b/gi, replacement: 'ensure' },
  { pattern: /\bplease make sure\b/gi, replacement: 'ensure' },
  { pattern: /\bplease verify\b/gi, replacement: 'verify' },
  { pattern: /\bplease confirm\b/gi, replacement: 'confirm' },
  { pattern: /\bplease note\b/gi, replacement: 'note:' },
  { pattern: /\bplease be aware\b/gi, replacement: 'note:' },
  { pattern: /\bplease keep in mind\b/gi, replacement: 'note:' },
  { pattern: /\bit is worth noting\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to note\b/gi, replacement: 'note:' },
  { pattern: /\bit should be noted\b/gi, replacement: 'note:' },
  { pattern: /\bit must be noted\b/gi, replacement: 'note:' },
  { pattern: /\bit is worth mentioning\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to mention\b/gi, replacement: 'note:' },
  { pattern: /\bit should be mentioned\b/gi, replacement: 'note:' },
  { pattern: /\bit must be mentioned\b/gi, replacement: 'note:' },
  { pattern: /\bit is worth pointing out\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to point out\b/gi, replacement: 'note:' },
  { pattern: /\bit should be pointed out\b/gi, replacement: 'note:' },
  { pattern: /\bit must be pointed out\b/gi, replacement: 'note:' },
  { pattern: /\bit is worth emphasizing\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to emphasize\b/gi, replacement: 'note:' },
  { pattern: /\bit should be emphasized\b/gi, replacement: 'note:' },
  { pattern: /\bit must be emphasized\b/gi, replacement: 'note:' },
  { pattern: /\bit is worth highlighting\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to highlight\b/gi, replacement: 'note:' },
  { pattern: /\bit should be highlighted\b/gi, replacement: 'note:' },
  { pattern: /\bit must be highlighted\b/gi, replacement: 'note:' },
  { pattern: /\bit is worth stressing\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to stress\b/gi, replacement: 'note:' },
  { pattern: /\bit should be stressed\b/gi, replacement: 'note:' },
  { pattern: /\bit must be stressed\b/gi, replacement: 'note:' },
  { pattern: /\bit is worth underlining\b/gi, replacement: 'note:' },
  { pattern: /\bit is important to underline\b/gi, replacement: 'note:' },
  { pattern: /\bit should be underlined\b/gi, replacement: 'note:' },
  { pattern: /\bit must be underlined\b/gi, replacement: 'note:' },
];

const EMAIL: Rule[] = [
  { pattern: /\bthanks in advance\b/gi, replacement: 'thanks' },
  { pattern: /\bthank you in advance\b/gi, replacement: 'thanks' },
  { pattern: /\bjust following up\b/gi, replacement: 'follow-up' },
  { pattern: /\bI am writing to\b/gi, replacement: '' },
  { pattern: /\bI'm writing to\b/gi, replacement: '' },
  { pattern: /\bI am reaching out to\b/gi, replacement: '' },
  { pattern: /\bI'm reaching out to\b/gi, replacement: '' },
  { pattern: /\bI am contacting you to\b/gi, replacement: '' },
  { pattern: /\bI'm contacting you to\b/gi, replacement: '' },
  { pattern: /\bI am getting in touch to\b/gi, replacement: '' },
  { pattern: /\bI'm getting in touch to\b/gi, replacement: '' },
  { pattern: /\bI wanted to reach out\b/gi, replacement: '' },
  { pattern: /\bI wanted to get in touch\b/gi, replacement: '' },
  { pattern: /\bI wanted to contact you\b/gi, replacement: '' },
  { pattern: /\bI wanted to follow up\b/gi, replacement: '' },
  { pattern: /\bI wanted to check in\b/gi, replacement: '' },
  { pattern: /\bI wanted to touch base\b/gi, replacement: '' },
  { pattern: /\bI wanted to connect\b/gi, replacement: '' },
];

const RESEARCH_NOTES: Rule[] = [
  { pattern: /\bit is worth noting that\b/gi, replacement: 'note:' },
  { pattern: /\ba large number of\b/gi, replacement: 'many' },
  { pattern: /\ba great number of\b/gi, replacement: 'many' },
  { pattern: /\ba great deal of\b/gi, replacement: 'much' },
  { pattern: /\ba large amount of\b/gi, replacement: 'much' },
  { pattern: /\ba significant amount of\b/gi, replacement: 'much' },
  { pattern: /\ba substantial amount of\b/gi, replacement: 'much' },
  { pattern: /\ba considerable amount of\b/gi, replacement: 'much' },
  { pattern: /\ban appreciable amount of\b/gi, replacement: 'much' },
  { pattern: /\ba small number of\b/gi, replacement: 'few' },
  { pattern: /\ba small amount of\b/gi, replacement: 'little' },
  { pattern: /\ba limited number of\b/gi, replacement: 'few' },
  { pattern: /\ba limited amount of\b/gi, replacement: 'little' },
  { pattern: /\bthe vast majority of\b/gi, replacement: 'most' },
  { pattern: /\bthe overwhelming majority of\b/gi, replacement: 'most' },
  { pattern: /\bthe great majority of\b/gi, replacement: 'most' },
  { pattern: /\bthe large majority of\b/gi, replacement: 'most' },
  { pattern: /\bthe vast bulk of\b/gi, replacement: 'most' },
  { pattern: /\bthe bulk of\b/gi, replacement: 'most' },
  { pattern: /\bthe greater part of\b/gi, replacement: 'most' },
  { pattern: /\bthe largest part of\b/gi, replacement: 'most' },
  { pattern: /\bthe lion's share of\b/gi, replacement: 'most' },
  { pattern: /\bthe preponderance of\b/gi, replacement: 'most' },
];

const ALL_PACKS: Record<string, Rule[]> = {
  common: COMMON,
  'agent-prompts': AGENT_PROMPTS,
  'project-specs': PROJECT_SPECS,
  'docs-readme': DOCS_README,
  email: EMAIL,
  'research-notes': RESEARCH_NOTES,
};

export function proseRewrite(input: string, pack: string, shouldReplace?: (match: string) => boolean) {
  return applyRules(input, `prose-rewrite:${pack}`, 'medium', ALL_PACKS[pack] ?? [], shouldReplace);
}
