import type { CompressionProfile } from './types';

const BASE_PROTECTED: CompressionProfile['protectedSpanTypes'] = [
  'fenced-code',
  'inline-code',
  'url',
  'file-path',
  'cli-command',
  'env-var',
  'api-placeholder',
  'number-unit',
  'json-block',
  'yaml-toml',
  'markdown-table',
  'markdown-heading',
  'email',
  'quoted-string',
];

export const PROFILES: CompressionProfile[] = [
  {
    id: 'lossless-light',
    label: 'Lossless Light',
    description: 'Structural cleanup only, normalized roundtrip.',
    reversible: true,
    guarantee: 'normalized-roundtrip',
    risk: 'safe',
    requiresLegend: false,
    enabledTransforms: ['normalize-structural'],
    protectedSpanTypes: BASE_PROTECTED,
    normalization: 'light-structural',
  },
  {
    id: 'lossless-dict',
    label: 'Lossless Dictionary',
    description: 'Reversible dictionary token substitution with legend.',
    reversible: true,
    guarantee: 'normalized-roundtrip',
    risk: 'low',
    requiresLegend: true,
    enabledTransforms: ['normalize-structural', 'dictionary'],
    protectedSpanTypes: BASE_PROTECTED,
    normalization: 'light-structural',
  },
  {
    id: 'lossy-prose',
    label: 'Lossy Prose',
    description: 'One-way prose simplification for generic text.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'article-removal', 'prose-rewrite:common'],
    protectedSpanTypes: BASE_PROTECTED,
  },
  {
    id: 'lossy-agent',
    label: 'Lossy Agent',
    description: 'One-way aggressive prompt-oriented shortening.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'high',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'article-removal', 'prose-rewrite:agent-prompts', 'abbreviation', 'operator'],
    protectedSpanTypes: BASE_PROTECTED,
  },
  {
    id: 'docs-readme',
    label: 'Docs / README',
    description: 'Conservative docs simplification while preserving markdown structure.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'low',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:docs-readme'],
    protectedSpanTypes: BASE_PROTECTED,
  },
  {
    id: 'codebase-context',
    label: 'Codebase Context',
    description: 'Protect code-like spans and abbreviate engineering terms.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['abbreviation', 'prose-rewrite:project-specs'],
    protectedSpanTypes: BASE_PROTECTED,
  },
  {
    id: 'meeting-notes',
    label: 'Meeting Notes',
    description: 'Reduce filler while preserving names, dates, and numbers.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:common'],
    protectedSpanTypes: BASE_PROTECTED,
  },
  {
    id: 'research-notes',
    label: 'Research Notes',
    description: 'Conservative simplification with citation and number safety.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'low',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:research-notes'],
    protectedSpanTypes: BASE_PROTECTED,
  },
  {
    id: 'spec',
    label: 'Spec',
    description: 'Very conservative requirement-preserving compression.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'low',
    requiresLegend: false,
    enabledTransforms: ['filler-removal'],
    protectedSpanTypes: BASE_PROTECTED,
  },
  {
    id: 'chat-history',
    label: 'Chat History',
    description: 'Remove pleasantries and compress speaker labels where safe.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:email', 'abbreviation'],
    protectedSpanTypes: BASE_PROTECTED,
  },
];

export function listProfiles(): CompressionProfile[] {
  return PROFILES;
}

export function getProfile(id: string): CompressionProfile | undefined {
  return PROFILES.find((profile) => profile.id === id);
}
