import type { CompressionProfile } from './types';

const BASE_PROTECTED: CompressionProfile['protectedSpanTypes'] = [
  'fenced-code',
  'inline-code',
  'url',
  'file-path',
  'cli-command',
  'env-var',
  'api-placeholder',
  'number-unit',
  'json-block',
  'yaml-toml',
  'markdown-table',
  'markdown-heading',
  'email',
  'quoted-string',
];

export const PROFILES: CompressionProfile[] = [
  {
    id: 'lossless-light',
    label: 'Lossless Light',
    description: 'Structural cleanup only, normalized roundtrip.',
    reversible: true,
    guarantee: 'normalized-roundtrip',
    risk: 'safe',
    requiresLegend: false,
    enabledTransforms: ['normalize-structural'],
    protectedSpanTypes: BASE_PROTECTED,
    normalization: 'light-structural',
    audienceGuidance: 'Best for prompts when you need guaranteed safe normalization.',
    expectedSavingsPct: [4, 12],
    recommended: true,
  },
  {
    id: 'lossless-dict',
    label: 'Lossless Dictionary',
    description: 'Reversible dictionary token substitution with legend.',
    reversible: true,
    guarantee: 'normalized-roundtrip',
    risk: 'low',
    requiresLegend: true,
    enabledTransforms: ['normalize-structural', 'dictionary'],
    protectedSpanTypes: BASE_PROTECTED,
    normalization: 'light-structural',
    audienceGuidance: 'Best for repetitive contexts that must be restored exactly to normalized baseline.',
    expectedSavingsPct: [8, 22],
    recommended: false,
  },
  {
    id: 'lossy-prose',
    label: 'Lossy Prose',
    description: 'One-way prose simplification for generic text.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'article-removal', 'prose-rewrite:common'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Best for prompt drafting when moderate wording changes are acceptable.',
    expectedSavingsPct: [12, 28],
    recommended: false,
  },
  {
    id: 'lossy-agent',
    label: 'Lossy Agent (Advanced)',
    description: 'One-way aggressive prompt-oriented shortening.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'high',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'article-removal', 'prose-rewrite:agent-prompts', 'abbreviation', 'operator'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Higher semantic risk. Use only when maximizing compression is more important than wording fidelity.',
    expectedSavingsPct: [20, 40],
    recommended: false,
    advanced: true,
  },
  {
    id: 'docs-readme',
    label: 'Docs / README',
    description: 'Conservative docs simplification while preserving markdown structure.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'low',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:docs-readme'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Best for docs and README material with conservative reductions.',
    expectedSavingsPct: [8, 20],
    recommended: true,
  },
  {
    id: 'codebase-context',
    label: 'Codebase Context',
    description: 'Protect code-like spans and abbreviate engineering terms.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['abbreviation', 'prose-rewrite:project-specs'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Best for engineering context blocks and repo walkthrough prompts.',
    expectedSavingsPct: [10, 24],
    recommended: true,
  },
  {
    id: 'meeting-notes',
    label: 'Meeting Notes',
    description: 'Reduce filler while preserving names, dates, and numbers.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:common'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Best for converting verbose notes into compact AI-ready context.',
    expectedSavingsPct: [12, 26],
    recommended: true,
  },
  {
    id: 'research-notes',
    label: 'Research Notes',
    description: 'Conservative simplification with citation and number safety.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'low',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:research-notes'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Best for literature summaries where citations and quantified claims must stay stable.',
    expectedSavingsPct: [6, 16],
    recommended: false,
  },
  {
    id: 'spec',
    label: 'Spec',
    description: 'Very conservative requirement-preserving compression.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'low',
    requiresLegend: false,
    enabledTransforms: ['filler-removal'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Best for requirements/spec text where ambiguity is costly.',
    expectedSavingsPct: [5, 14],
    recommended: false,
  },
  {
    id: 'chat-history',
    label: 'Chat History',
    description: 'Remove pleasantries and compress speaker labels where safe.',
    reversible: false,
    guarantee: 'semantic-lossy',
    risk: 'medium',
    requiresLegend: false,
    enabledTransforms: ['filler-removal', 'prose-rewrite:email', 'abbreviation'],
    protectedSpanTypes: BASE_PROTECTED,
    audienceGuidance: 'Best for reducing long conversations before passing to agents.',
    expectedSavingsPct: [12, 30],
    recommended: false,
  },
];

export function listProfiles(): CompressionProfile[] {
  return PROFILES;
}

export function getProfile(id: string): CompressionProfile | undefined {
  return PROFILES.find((profile) => profile.id === id);
}
